### ISSUE TITLE
Adding multi-core functionality to summarize_draws

### ISSUE THREAD

**Issue by saudiwin** [stan-dev/posterior#124]
Hi - 

This certainly falls into the realm of feature request. I am using posterior and enjoying the functionality, but when there are a lot of parameters some functions like `summarize_draws` (not apologizing for the American spellling :) can take a long time. Given that these are doing parameter by parameter calculations, would it be possible to convert one of the loops to be an mclapply loop with an optional mc.cores argument? Could save a lot of time with models with lots of parameters.

Also here is some code that implements this. If there is interest I can do a PR:

```
library(posterior)
library(dplyr)

obj <- example_draws()

summarize_draws_mc <- function(obj,  ..., cores=parallel::detectCores()) {
  
  varlist <- dimnames(obj)$variable
  
  # find an optimal-ish breakdown of variable names
  
  var_break <- floor(length(varlist)/cores)
  var_extra <- length(varlist) %% cores
  
  var_splits <- c(rep(1:cores,each=var_break),
                  1:var_extra)
  
  
  over_vars <- parallel::mclapply(1:cores, function(c,...){
    
    subset_draws(obj,variable=varlist[var_splits==c]) %>% 
      summarize_draws(...)
    
  },mc.cores=cores) %>% 
    bind_rows
  
  slice(over_vars,match(varlist,variable))
  
}

sum_obj <- summarize_draws(obj)
sum_obj_mc <- summarize_draws_mc(obj)

identical(sum_obj,sum_obj_mc)

#check time differences

time1 <- system.time(summarize_draws(obj))
time2 <- system.time(summarize_draws_mc(obj))

time1
time2

# not particularly efficient, but should speed up with more variables/parameters

```

**Comment by jgabry** [comment]
Yeah I think parallelization is something we should consider. Anyone have a reason why we shouldn't do this?

**Comment by jsocolar** [comment]
This is closely related to https://github.com/stan-dev/posterior/issues/98.  It turns out that there's a big speedup available even from splitting up the computation *without* using multiple cores.  I'll have a bit more on that issue shortly.

**Comment by saudiwin** [comment]
I think that @jsocolar re-writing of the function would make it much more scalable. I do still think that multicore functionality would still be useful given how easy it is to implement esp. with the R parallel package. It is true it won't work on Windows but it's also super easy to code. Of course I can always maintain a separate wrapper even if it's not in the main package.

**Comment by jsocolar** [comment]
https://github.com/stan-dev/posterior/pull/138 rewrites `summarise_draws` for efficiency but does not include any parallel processing. 

To add parallel processing, my understanding is that the preferred solution is via the `future` package.  This leaves two questions:
1. Do we want to add a `cores` argument (defaulting to 1) directly in `summarise_draws`, or do we want a separate function `parsummarise_draws` that is a wrapper for `summarise_draws`?  
2. forked processes don't always play nice with Rstudio.  See https://github.com/HenrikBengtsson/future/issues/299 and https://github.com/rstudio/rstudio/issues/2597 . Thus the future package defaults to not allowing forked processes on Rstudio.  On the other hand, I've never had a problem with my personal `parsummarise_draws` function which uses `parallel::mclapply`, despite that I've run it from Rstudio many times.  And for gargantuan draws arrays where parallelism is most helpful, the performance/memory gains from forking might matter.  So do we want to follow future and disable forking from within Rstudio by default, or not?

**Comment by mjskay** [comment]
I believe recommended best practices with future are to leave the evaluation plan up to the user (thus no cores argument). See here: https://cran.r-project.org/web/packages/future/vignettes/future-7-for-package-developers.html

**Comment by jgabry** [comment]
(I'm not an expert on parallelization, so take this all with a grain of salt and feel free to tell me that I don't know what I'm talking about)

I agree with @mjskay that if we use future we should adhere to the best practices. However, there are a few things I don't love about depending on future (it may still end up as the best option but just throwing these things out there): 

* `future::plan(multisession)` and friends default to using _all_ available cores. That seems (maybe) fine for non-interactive use, but for use interactively it seems bad to default to taking all cores when the user will probably be doing other things on their computer that require some resources. To avoid this it's of course possible to just specify the `workers` argument to `future::multisession`, but the default not being "safe" is concerning to me. On the other hand, an argument `cores` defaulting to 1 is always safe and the user can change it to get speedups. 

* making the user explicitly set up the "plan" by calling functions from future seems like it interrupts the workflow and forces the introduction of code not conceptually related to the task at hand (i.e., not conceptually related to posterior distributions and summaries). For example compare these two options here based on ease of reading: 

```r
s <- summarise_draws(x, cores = 2)
s$mean 

# versus 

future::plan("multisession", workers = 2)
s <- summarise_draws(x)
future::plan("sequential") # not strictly necessary but a good idea to reset unless more calls to summarise_draws are planned in the near future
s$mean
```

The second is more explicit (but 99% of users won't care _how_ the parallelization is done, so the info is superfluous), but I'd say it's much less clear / much harder to read. 

To avoid these issues:  in the loo package we use `parallel::mclapply()` for non-windows and `parallel::parLapply()` for windows and the user never needs to mess with any of it. It's all done behind the scenes and they just bump `cores` to whatever value they want. Of course, if future is much better than the parallel package (it very well might be but it's not my area of expertise) then it could be worth using it instead of the parallel package despite these drawbacks. 

So I'm not against using future, just wanted to put these concerns out there.

**Comment by jsocolar** [comment]
I very strongly agree that we don't want to force the user to set up the parallelization explicitly, other than either specifying a `cores` argument to `summarise_draws` or using a separate `parsummarise_draws` function.  Something important to consider is that many potentially users who've not encountered much parallelization before will nevertheless have experience setting the `cores` argument in cmdstanr.

Thus, I feel pretty strongly that either we should deviate from the published best practices using `future`, or we should stick with `parallel`.  

If we just use `parallel` there would still be a question of whether we want to fork by default on OSX/Linux even from within Rstudio.

**Comment by jsocolar** [comment]
Ok, I had some spare time/enthusiasm, so I went ahead and gave this a crack.  I've got a working implementation that gives the expected speedup and passes the tests that I wrote for it, at least on OSX.  I don't want to get ahead of the design discussion here, so I've refrained from making a PR.  Perhaps  @jgabry @paul-buerkner @mjskay could take a look (no rush) and if you'd like me to open a PR I'd be glad.
https://github.com/jsocolar/posterior/tree/parallel

Highlights are:
* A new `parsummarise_draws()` function (and associated `parsummarize_draws()` with a z) that is a drop-in replacement for `summarise_draws()`, with appropriate methods, etc. Behavior should be (is believed to be) identical to `summarise_draws()` except that there's a `cores` argument for parallel processing.  `parsummarise_draws()` is basically just a wrapper for `summarise_draws()`.  There is no `parsummary()` to replace `summary()`, but I think that's fine?
* Multicore processing achieved by mimicking `loo` with
```
  if (checkmate::test_os("windows")) {
    cl <- parallel::makePSOCKcluster(cores)
    on.exit(parallel::stopCluster(cl))
    summary_list <- parallel::parLapply(chunk_list, summarise_draws2, cl = cl)
  } else {
    summary_list <- parallel::mclapply(chunk_list, summarise_draws2, mc.cores = cores)
  }
  ```
  * Tests at test-parsummarise_draws.R that check for equivalency to `summarise_draws()` output for every test case in test-summarise_draws.R, plus additional tests to check cases where one or more core doesn't receive any variables to process.

**Comment by paul-buerkner** [comment]
I agree with the notion of using parallel rather than future for the reasons you listed above. 

Please open a PR to implement this if you like. Just one question right now: Do you plan on adding a new function that is not `summarize_draws` itself? From my understanding, this is what you were suggesting. How abouut just adding a `.cores` argument to `summarize_draws` so that the user interface stays exactly the same just with an added argument (defaulting to `.cores = 1`)? Or is that already what you had in mind?

**Comment by jsocolar** [comment]
In the current implementation I have a new function called `parsummarise_draws()`, but this was mostly so that I could easily test for equality of output between `summarise_draws()` and `parsummarise_draws()`.  I can now bring all of `parsummarise_draws()` inside `summarise_draws()`.  The idea, I assume, should be to handle the `cores = 1` case separately from multi-core, so that we can suggest rather than require `parallel`?

**Comment by paul-buerkner** [comment]
Since `parallel` is a core R package, every R user will have it installed anyway, so I wouldn't be worried about putting in in `imports`. @jgabry what's your opinion on this?

**Comment by jsocolar** [comment]
Actually, I just realized that I don't know what `cl <- makePSOCKcluster(1)` actually does.  Perhaps it's best to keep the `cores = 1` case separate anyway.

**Comment by paul-buerkner** [comment]
There are different kinds of separations of course, so my tendeny would be to have as little code duplication as possible.

**Comment by jgabry** [comment]
> Since `parallel` is a core R package, every R user will have it installed anyway, so I wouldn't be worried about putting in in `imports`. @jgabry what's your opinion on this?

Yeah I think either Imports or Suggests is fine in this case.

**Comment by mike-lawrence** [comment]
So I failed to check here (or the docs!) to see if this was implemented already before playing with a few different approaches myself 🤦 At least I can confirm that @jsocolar's solution is indeed the fastest! I might take a look though at the possibilities for adding a progress bar like the clustermq approach provides. For posterity, here's code comparing methods:

```r
# choose method to test ----

#options:
#	'serial'
#		- regular ol' serial compute
#	'multidplyr'
#		- uses https://github.com/tidyverse/multidplyr
#	'clustermq'
#		- uses https://github.com/mschubert/clustermq
#		- has nice progress bar
#		- supposed to be low-overhead
#		- seemingly crash-prone
#	'posterior'
#		- uses the parallelism implemented directly in posterior

#uncomment desired option below:
method = (
	  # 'serial'     # times: 109s, 110s
	  # 'multidplyr' # times: #53s, 52s
	  # 'clustermq'  # times: 53s, 55s
	  # 'posterior'    # times: 38s, 38s, 39s *winner*
)

# libs & user defined functions ----
library(tidyverse)
library(magrittr)
system_time = function(x){print(system.time(x))}

# get_par_dxs: function to check parameter diagnostics (rhat, _ess)
get_par_dxs = function(x,nchains){
	x = matrix(x,ncol=nchains)
	tibble::tibble(
		rhat = posterior::rhat(x)
		, ess_bulk = posterior::ess_bulk(x)
		, ess_tail = posterior::ess_tail(x)
	)
}

# importing posterior samples ----
#   n.b. aria::coda() yields a tibble of the same format as the cmdstan csvs
if(!file.exists('post.qs')){
	(
		aria::coda("sampled_2way.qs")
		%>% filter(!warmup)
		%>% select(
			-warmup
			, -ends_with('__')
		)
		%>% select(
			chain
			, iteration
			, starts_with('z_')
			, starts_with(fixed('r.'))
		)
		%>% pivot_longer(
			cols = c(-chain,-iteration)
			, names_to = 'variable'
		)
		%>% group_by(variable)
	) ->
		post
	qs::qsave(post,'post.qs',preset='fast')
}else{
	post = qs::qread('post.qs')
}

# run the chosen method ----
if(method == 'serial'){
	system_time(
		(
			post
			%>% summarise(
				get_par_dxs(
					x = value
					, nchains = length(unique(chain))
				)
			)
		) ->
			par_dxs
	)
}

if(method == 'multidplyr'){
	system_time(cluster <- multidplyr::new_cluster(parallel::detectCores()/2-1))
	system_time(multidplyr::cluster_assign(cluster, get_par_dxs = get_par_dxs))
	system_time(
		post %<>% multidplyr::partition(cluster)
	)
	system_time(
		(
			post
			%>% summarise(
				get_par_dxs(
					x = value
					, nchains = length(unique(chain))
				)
			)
		) ->
			par_dxs
	)
	system_time( par_dxs %<>% collect() )
}

if(method == 'clustermq'){
	options(clustermq.scheduler = "multicore")
	system_time(
		post %<>% group_split()
	)
	system_time(
		(
			clustermq::Q(
				x = post
				, fun = function(x){
					z = get_par_dxs(
						x$value
						,nchains = length(unique(x$chain))
					)
					z$variable = x$variable[1]
					return(z)
				}
				, n_jobs = parallel::detectCores()/2-1
				# , chunk_size = floor(length(post)/(parallel::detectCores()/2-1)/10)
			)
		) ->
			par_dxs
	)
	system_time(
		par_dxs %<>% bind_rows()
	)
}

if(method=='posterior'){
	#posterior wants a wide format
	(
		post
		%>% pivot_wider(names_from=variable)
		%>% rename(
			.chain = chain
			, .iteration = iteration
		)
		%>% posterior::as_draws()
	) -> post
	system_time(
		(
			post
			%>% posterior::summarise_draws(
				posterior::default_convergence_measures()
				, .cores = parallel::detectCores()/2-1
			)
		) -> par_dxs
	)
}
```

**Comment by jgabry** [comment]
> For posterity, here's code comparing methods:

Thanks @mike-lawrence!
