### ISSUE TITLE
after subsetting row names don't match when converting list to df 

### ISSUE THREAD

**Issue by jgabry** [stan-dev/posterior#134]
```r
x_df <- as_draws_df(example_draws())
x_list <- as_draws_list(example_draws())

# all good here
all.equal(rownames(x_df), rownames(as_draws_df(x_list))) 

# now call subset_draws
x_df_sub <- subset_draws(x_df)          
x_list_sub <- subset_draws(x_list)

# "400 string mismatches"
all.equal(rownames(x_df_sub), rownames(as_draws_df(x_list_sub)))
```

This doesn't matter a ton since we don't use the row names for anything meaningful, but I guess the question is whether we should make the row names of `as_draws_df(x_list_sub)` the same as the ones of `x_df_sub` or if we should NULL them out in both cases.

**Comment by Ozan147** [comment]
`as_draws_df()` encodes repeated iterations from each chain as row names: 
```r
# Row names are of the form "chain.iteration"
> rownames(as_draws_df(example_draws()))
[1] "1.1"   "1.2"   "1.3"   "1.4"   "1.5"   "1.6"   "1.7"   "1.8"   "1.9"   "1.10" 
...
[111] "2.11"  "2.12"  "2.13"  "2.14"  "2.15"  "2.16"  "2.17"  "2.18"  "2.19"  "2.20" 
...
```
Only exception to this is `as_draws_df.draws_matrix()` because it explicitly sets row names to `NULL`:
https://github.com/stan-dev/posterior/blob/4646eedaae2e26655031e9f679623f3cbfe2d8b4/R/as_draws_df.R#L66
```r
> rownames(as_draws_df(as_draws_matrix((example_draws()))))
[1] "1"   "2"   "3"   "4"   "5"   "6"   "7"   "8"   "9"   "10"
...
```
I believe it makes sense to repeat this for other classes of the `as_draws_df` method as @paul-buerkner suggested [here](https://github.com/stan-dev/posterior/pull/128#issuecomment-841332912) and @jgabry mentioned above.

**Comment by jgabry** [comment]
Thanks for looking into this. Setting them to NULL sounds fine to me.

**Comment by paul-buerkner** [comment]
same for me, NULL is fine.

Jonah Gabry ***@***.***> schrieb am Fr., 14. Mai 2021, 19:07:
