### ISSUE TITLE
Should we rename `draws_rvars()` as `draws_rvar()`?

### ISSUE THREAD

**Issue by Ozan147** [stan-dev/posterior#155]
All sub-classes of `draws` has the `draws_{parent}` singular naming structure except for `draws_rvars`. Is this intentional to stress that `draws_rvar` can hold multiple `rvar` objects? The singular version still seems more consistent to me.

> array -> draws_array
> df -> draws_df
> list -> draws_list
> matrix -> draws_matrix
> rvar -> draws_rvar

**Comment by paul-buerkner** [comment]
I would tend to disagree on this. The reason we call it `draws_matrix`, `draws_array` etc. is that those are actually valid objects of parent class `matrix`, `array`, etc. However, `draws_rvar` does not have `rvar` as parent class but is actually a **list** of `rvar`s. Hence the name `draws_rvars`. What do others, in particular @mjskay, think?

**Comment by mjskay** [comment]
Yes, I agree with @paul-buerkner's logic, which reflects our original discussion of this issue where we considered both names. I would add that I read "draws_x" as "adjective_noun" which makes sense for "draws_rvars" but not for "draws_rvar" because the noun in this case is not one rvar but multiple rvars.

**Comment by Ozan147** [comment]
Sounds good, it makes sense. Sorry for bringing up already discussed/resolved questions 😅

**Comment by paul-buerkner** [comment]
No worries, we very much appreciate your work and thoughts you put into posterior!
