### ISSUE TITLE
`as_draws_rvars` on a list of data frames

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/posterior#192]
I am trying to fix issue https://github.com/stan-dev/cmdstanr/issues/536 which is essentially supporting `draws_rvars` directly in cmdstanr and have bumped into a problem for which I have a solution but I dont really like it and am wondering if anything can be done about this in the posterior package.

This is a script that resembles what cmdstanr does internally, read the CSV files to a list of data frames. This is the fastest and most RAM friendly:

```r
library(cmdstanr)
library(posterior)

fit <- cmdstanr_example(example = "logistic")

draws <- list()
i <- 1
for(out_file in fit$output_files()) {
  fread_cmd <- paste0("grep -v '^#' '", out_file, "'")
  draws[[i]] <- data.table::fread(cmd = fread_cmd, data.table = FALSE)
  i <- i + 1
}
```

After this we run the `as_draws_*` on that list (depending on the selected format or as_draws_array by default) and this is currently supported for all formats except for rvars. The problem is that running `as_draws_rvars` directly on this list errors (second line below), while if I first pass it through any of the others, it works (the last line).

```r
> a <- as_draws_list(draws)
> b <- as_draws_rvars(draws) 
Error: Can't convert <data.frame> to <rvar<1>>.
Run `rlang::last_error()` to see where the error occurred.

> c <- as_draws_rvars(as_draws_list(draws))
```

Is there anything that can be done to support this use case directly. Its not a huge deal if we need to pass it through another format, but would be great if we can avoid it. Thanks!

**Comment by mjskay** [comment]
Yeah, I see the problem --- draws_rvars has a custom function for lists in case people want to pass in lists of rvars. Probably this should check if the input is a list of rvars and otherwise fall back to the default behavior.

If I understand correctly what you are doing, you are basically building an object with the same structure as the draws_list format. The upshot is as_draws_XXX is (except with rvars due to this bug) going to detect that you've passed it a list and try to convert that to the closest format first, i.e. draws_list. E.g. `as_draws_array(draws)` is basically equivalent to `as_draws_array(as_draws_list(draws))`, so you don't gain any performance by avoiding the call to `as_draws_list()`, which should be fast anyway.

You can see this with some benchmarks: `as_draws_list()` is quite fast because it doesn't have to really touch the data, everything else goes through `as_draws_list()` internally and is no faster than passing through `as_draws_list()` up front:

```r
bench::mark(
    as_draws_list(draws), as_draws_array(draws), as_draws_array(as_draws_list(draws)), as_draws_matrix(draws), as_draws_matrix(as_draws_list(draws)), as_draws_rvars(as_draws_list(draws)), check = FALSE
)
```
```
# A tibble: 6 x 13
  expression                                 min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc
  <bch:expr>                            <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int> <dbl>
1 as_draws_list(draws)                   330.1us  356.3us     2693.    6.25KB    10.8   1252     5
2 as_draws_array(draws)                   4.63ms   5.66ms      178.    2.36MB    11.4     78     5
3 as_draws_array(as_draws_list(draws))    4.61ms    4.9ms      202.    2.36MB    16.6     85     7
4 as_draws_matrix(draws)                  2.66ms   2.82ms      344. 1017.46KB     8.66   159     4
5 as_draws_matrix(as_draws_list(draws))   2.65ms   2.84ms      336. 1017.46KB     9.50   106     3
6 as_draws_rvars(as_draws_list(draws))    3.97ms   4.25ms      231.    1.49MB     8.71   106     4
# ... with 5 more variables: total_time <bch:tm>, result <list>, memory <list>, time <list>,
#   gc <list>
```

So we should fix this for consistency's sake (I will submit a PR), but the workaround of using `as_draws_rvars(as_draws_list(draws))` should be no slower than the fix.

**Comment by rok-cesnovar** [comment]
Thank you for the explanation. This makes sense to me now.

> If I understand correctly what you are doing, you are basically building an object with the same structure as the draws_list format.

Yeah, this turned out to be the fastest and memory friendly way for combining multiple chains with a lot of parameters/iterations. There was way too much copies at first when we used arrays and binding them chain by chain.

> So we should fix this for consistency's sake (I will submit a PR), but the workaround of using as_draws_rvars(as_draws_list(draws)) should be no slower than the fix.

It will also make the cmdstanr implementation cleaner so thank you for the PR!

**Comment by mjskay** [comment]
No problem!
