### ISSUE TITLE
issue with 0-sized rvars

### ISSUE THREAD

**Issue by wds15** [stan-dev/posterior#242]
0-sized rvars behave unexpectedly as they look like 1-sized rvars and they even throw errors when converted to a matrix:

```R
mu <- as_rvar(rep(0, 0))
mu
as_draws_matrix(mu)
```

produces:

```R
> mu <- as_rvar(rep(0, 0))
> mu
rvar<1>[0] mean ± sd:
NULL
> as_draws_matrix(mu)
Error in dimnames(draws_of(x)) <- `*vtmp*` : 
  length of 'dimnames' [2] not equal to array extent
```

I would expect to get a 0 sized rvar (not a 1-sized as it looks) and when converting to a matrix I would expect to get a matrix with 0 columns and rows as many as there are samples (0 in this case).

**Comment by mjskay** [comment]
The NULL rvar is 0-sized (in the sense of length): it is "one draw of nothing", i.e. it is backed by a 1 x 0 matrix:

```r
> length(rvar(NULL))
[1] 0
> dim(draws_of(rvar(NULL)))
[1] 1 0
```

This format for the NULL rvar was chosen because it simplified the code for indexing (e.g. extending a NULL rvar via `x[1] = ...` works without special cases because of this). 

One question might be if "one draw of nothing" is the right semantics for the NULL rvar; in theory anything where `prod(dim(draws_of(x))) == 0` is a "NULL" rvar; currently any such object is converted to the "canonical" form of a 1 x 0 draws array. The other obvious alternative would be a 0 x 0 array ("zero draws of nothing"), or to allow multiple "NULL"s with different numbers of draws.

Incidentally looking at this has caused me to discover another bug, which is that because of this normalization of "NULL"s, `draws_rvars` containing NULL rvars where other variables have ndraws != 1 are malformed:

```r
> draws_rvars(x = rvar(NULL), y = rvar(rnorm(100)))
# A draws_rvars: 1 iterations, 1 chains, and 2 variables
$x: rvar<1>[0] mean ± sd:
NULL

$y: rvar<100>[1] mean ± sd:
[1] 0.14 ± 0.92 
```

(x and y should both have the same number of draws).

Which probably means we shouldn't do this normalization, and should be keeping the number of draws as input for NULL rvars (except maybe for 0 x 0, if we want to be able to extended NULL rvar vectors). Which leads to the presence of multiple "NULL"ish rvars, but maybe this is okay. I've started a draft PR with this change here: #244

### Discussion and TODOs 

Remains to be discussed: should NULL rvars with 0 draws be allowed? I think that will require a bit more thought to figure out how to handle some corner cases with indexing (at the very least, if I turn it on a bunch of tests immediately fail ;) ).

Pros of converting 0-draws NULL to 1-draw NULL (the current behavior):
- It is consistent with the semantics of other "constant" rvars (which also have 1 draw): they can be used with other rvars of arbitrary numbers of draws because 1 draw can be broadcast to n draws. If we allow 0-draw rvars I'll need to special case broadcasting for draws I think.
- It simplifies the implementation of indexing corner cases (e.g. allows extending a NULL rvar easily via `x[1] = ...`, etc)

Cons:
- `ndraws(rvar(NULL))` reports `1` when perhaps it should report `0` for consistency with other formats (though it's not clear to me other formats even support intermixing `NULL` variables with non-`NULL` variables, so I'm not sure this matters that much). `length(rvar(NULL))` *does* report `0` as it should.

Remains to be done:
- fix conversion of NULL rvars to other formats

**Comment by wds15** [comment]
Difficult. If I look at what R does, then NULL is special and usually means "nothing". NA is different. Example:

![image](https://user-images.githubusercontent.com/12070126/177542405-2c11bc5b-eaff-4cf8-b111-660ef4c2a6e1.png)

**Comment by paul-buerkner** [comment]
Personally, I am fine with NULL rvars having 1 draw if the simplifies implementation and avoids handling a lot of edge cases. We can also document it as such if people are wondering. Thank you for working on this!

**Comment by wds15** [comment]
Maybe considering how other R things handle this helps?

![image](https://user-images.githubusercontent.com/12070126/177720575-7114e900-7ded-4513-9db1-c67e3a4af10b.png)

Not sure what the tidyverse style answer is.
