### ISSUE TITLE
Subsetting an rvar with an rvar

### ISSUE THREAD

**Issue by mattansb** [stan-dev/posterior#282]
@mjskay I absolutely love the `rvar` class! So much better than dealing with pesky vectors / matrices / arrays!

Is there a way to subset an `rvar` with an `rvar`?

If not, it would be great to be able to do something like this:

```R
library(posterior)

A <- rvar(rnorm(100))
B <- rvar(rnorm(100))

(idx <- A > B)
#> rvar<100>[1] mean ± sd:
#> [1] 0.44 ± 0.5

Pr(idx) # is logical
#> [1] 0.44

A[idx] # make a new rvar based only on the subset of samples for which idx is true
#> Error...
```

This would really be great for order restrictions (e.g., the type used in [C14 carbon dating](https://arxiv.org/pdf/1704.07141.pdf)...)

**Comment by mjskay** [comment]
Yeah - currently not, but something like this would be great! I've considered this and indexing with integer rvars before, but haven't gotten around to figuring it all out since I think it will take some care to get right. 

Since it can create situations where rvars of different numbers of chains/draws can be combined (which is currently not supported), we'd want to carefully sort out the semantics of it and make sure all the operations we support are valid (and raise warnings/errors for invalid cases). Eg it will probably have to require chains to be merged (or auto merge them), and I'm not sure what to require for the assignment version `x[y] <- z` in terms of how/whether chains of `x`, `y`, and `z` should conform.

**Comment by mjskay** [comment]
I've finished a very conservative implementation of this for subsetting (`[`) and subset-assignment (`[<-`): it supports only a single scalar logical rvar as an index, used to subset draws. After playing with it, I'm not even sure what the correct implementation for a numeric vector should be (selecting draws or selecting elements of the vector?), so I'm leaving that out for now. I'm honestly not 100% sure what I've come up with makes the most sense, but I tried to keep subsetting and subset-assignment consistent with each other.

Currently, the semantics are:
- `x[i]` for rvar `x` and scalar logical rvar `i` returns an rvar with the same shape as `x`, but subset to the draws with a value `TRUE` in `i`. `ndraws(i)` must be either 1 or `ndraws(x)`. The result has `dim(x[i]) = dim(x)` and `ndraws(x[i]) = sum(i)`.
- `x[i] <- y` for rvars `x`, `y` and scalar logical rvar `i` replaces each full (joint) draw in `x` where `i` is `TRUE` with the corresponding draw from `y`. `y` must have `dim(y) = dim(x)` and `ndraws(y) = sum(i)`, or be broadcastable to this shape.

I would love if some folks can play around with this and let me know if the semantics make sense.

**Comment by mattansb** [comment]
This looks right to me! I'll find some time to play around with it to see if it behaves like my mental model.

It would be great to find some archeologists and see if *they* find it useful. Other than that group, I know Richard Morey (and others?) had some work on order restrictions for estimating effects in psychology.

(I've never actually needed to use this myself, but wanted to demonstrate how it can be done in a Bayes class for undergrad stats)

(Also, I am aware that it is more efficient, MCMC-wise, to bake these restrictions into the Stan code.)

**Comment by mattansb** [comment]
I seem to be getting an error with some of the `as_draws_*()` functions:

``` r
library(posterior)
#> This is posterior version 1.4.1.9000
#> 
#> Attaching package: 'posterior'
#> The following objects are masked from 'package:stats':
#> 
#>     mad, sd, var
#> The following objects are masked from 'package:base':
#> 
#>     %in%, match
A <- rvar(rnorm(1000))
B <- rvar(rnorm(1000, mean = 0.4))

idx <- A > B


A[idx]
#> rvar<407>[1] mean ± sd:
#> [1] 0.65 ± 0.81

as_draws(A[idx])
#> # A draws_rvars: 407 iterations, 1 chains, and 1 variables
#> $x: rvar<407>[1] mean ± sd:
#> [1] 0.65 ± 0.81
as_draws_array(A[idx])
#> # A draws_array: 407 iterations, 1 chains, and 1 variables
#> , , variable = x
#> 
#>          chain
#> iteration      1
#>         1  0.039
#>         2  0.697
#>         3 -0.256
#>         4  0.362
#>         5  0.417
#> 
#> # ... with 402 more iterations
as_draws_matrix(A[idx])
#> # A draws_matrix: 407 iterations, 1 chains, and 1 variables
#>     variable
#> draw      x
#>   1   0.039
#>   2   0.697
#>   3  -0.256
#>   4   0.362
#>   5   0.417
#>   6  -0.428
#>   7   0.737
#>   8  -1.130
#>   9   1.256
#>   10 -0.386
#> # ... with 397 more draws
as_draws_rvars(A[idx])
#> # A draws_rvars: 407 iterations, 1 chains, and 1 variables
#> $x: rvar<407>[1] mean ± sd:
#> [1] 0.65 ± 0.81

as_draws_df(A[idx])
#> Error in `[[<-.data.frame`(`*tmp*`, ".chain", value = c(1L, 1L, 1L, 1L, : replacement has 999 rows, data has 407
as_draws_list(A[idx])
#> Error in `[[<-.data.frame`(`*tmp*`, ".chain", value = c(1L, 1L, 1L, 1L, : replacement has 999 rows, data has 407
```

<sup>Created on 2023-04-19 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by mjskay** [comment]
good catch, thanks! fixed.

**Comment by mjskay** [comment]
A few additional ideas in this vein that might be worth implementing occurred to me:

- `ifelse.rvar(test, yes, no)`, which would broadcast `test`, `yes`, and `no` (all rvars or castable to rvars) to a common shape and then do a vectorized ifelse on them. Might either make `ifelse()` generic or call this `rvar_ifelse()`.
- `y = x[[i]]` where `i` is a scalar numeric rvar would return a scalar rvar. If $x_{(n)}$ is the $n$-th draw of `x`, $y_{(n)}$ would be $x_{(n)}[[i_{(n)}]]$
- `y = x[i,j,...]` where `i`, `j`, ... are vector numeric rvars would return an rvar with `dim(y) = lengths(list(i, j, ...))` and $y_{(n)} = x_{(n)}[i_{(n)}, j_{(n)}, ...]$

**Comment by mattansb** [comment]
`rvar_ifelse()` implies a non-`rvar` `ifelse()` which I guess can be used to manipulate the actual vector or rvars?

(I did not understand the other two ideas you had)

I've been using the subsetting branch this week - really great, exactly what I had in mind!

**Comment by mjskay** [comment]
> rvar_ifelse() implies a non-rvar ifelse() which I guess can be used to manipulate the actual vector or rvars?

Good point, probably need some consistency here. I suppose a non-rvar version might allow `test` to be a logical vector instead of a logical rvar vector, and then `yes` and `no` would still be rvars (or castable-to-rvar). But then, the result would still be an `rvar`. So, given the naming scheme used elsewhere, this should perhaps still be something like `rvar_ifelse`... honestly, `rvar_ifelse` could be generic and have an implementation for `test` as an rvar and `test` as a base vector.

> (I did not understand the other two ideas you had)

The third idea probably won't happen any time soon anyway (I am realizing its implementation would probably be slow in pure R anyway, unless we dropped into C/C++). 

The second idea is just an attempt to generalize the `[[` operator... could use it to create mixtures, for example.
