### ISSUE TITLE
summarise_draws still prohibitively slow for very large models

### ISSUE THREAD

**Issue by huffyhenry** [stan-dev/posterior#284]
I have a Stan model with ~2 million parameters (~4 million together with transformed parameters). The workflow is:

```r
library(cmdstanr)

model <- cmdstan_model(...)
fit <- model$sample(...)
fit$cmdstan_diagnose()
s <- fit$summary(.cores=6)
```

This script hangs on the last line, using only 1 core (I killed it after a week). Presumably it’s stuck somewhere [here](https://github.com/stan-dev/posterior/blob/c58ea9fb2328d58227121b01e2a0469516cdc7a7/R/summarise_draws.R#L170). Issues #98 and #104 only considered models up to hundreds of thousands of parameters, and indeed `summarise_draws` works for me at that scale (still around 1 day, but that's acceptable). 

Thanks in advance for suggestions on how to get my draw summaries and diagnostics. Of course I can read the CSVs in myself, but I like `posterior` and would rather use your code if at all feasible.

_(cross-posting from the Stan discourse)_

**Comment by paul-buerkner** [comment]
Thank you for posting this issue. If `repair_draws` is the problem, we could add a switch that would deactivate repair checks (of figure out to make this scale less horribly). Can you check what happens in your case if you deactivate the line of code in a branch of posterior?

**Comment by mjskay** [comment]
Did a little bit of investigating here on performance with a `draws_matrix` (since that's what cmdstanr returns by default I think?).

`repair_draws()` seems to have constant-time performance in terms of number of variables when no repair is needed, which is good:

```r
library(posterior)

n = c(10, 100, 1000, 10000)
x_repaired = lapply(n, \(n) as_draws_matrix(rvar_rng(rnorm, n)))
x_unrepaired = lapply(x_repaired, \(x) {rownames(x) = sample(rownames(x)); x})

bench_mark_n = function(..., x = x_repaired) {
  dplyr::bind_rows(lapply(x, \(x){
    b = bench::mark(...)
    cbind(n = nvariables(x), b)
  }))
}

bench_mark_n(repair_draws(x))
# # A tibble: 4 × 14
#       n expression           min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc
#   <int> <bch:expr>      <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int> <dbl>
# 1    10 repair_draws(x)   3.97ms   4.28ms      230.     692KB     0      116     0
# 2   100 repair_draws(x)   3.97ms   4.29ms      231.     692KB     3.55    65     1
# 3  1000 repair_draws(x)   3.79ms   4.16ms      237.     692KB     0      119     0
# 4 10000 repair_draws(x)   3.92ms   4.29ms      231.     692KB     0      116     0
# # ℹ 5 more variables: total_time <bch:tm>, result <list>, memory <list>,
# #   time <list>, gc <list>
```

But when draws are unsorted, it degrades as `n` increases:

```r
bench_mark_n(repair_draws(x), x = x_unrepaired)
# # A tibble: 4 × 14
#       n expression           min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc
#   <int> <bch:expr>      <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int> <dbl>
# 1    10 repair_draws(x)   4.45ms   4.81ms    201.   1020.13KB        0   101     0
# 2   100 repair_draws(x)   5.69ms   6.56ms    152.      3.74MB        0    76     0
# 3  1000 repair_draws(x)  21.36ms   21.8ms     45.8    31.22MB        0    23     0
# 4 10000 repair_draws(x) 173.21ms 173.54ms      5.68  305.98MB        0     3     0
# # ℹ 5 more variables: total_time <bch:tm>, result <list>, memory <list>,
# #   time <list>, gc <list>
```

I did some profiling with `profvis` and the culprit here is this slice, which is only run if the draws are not sorted:

https://github.com/stan-dev/posterior/blob/59f4e6cbdddb9bb7b0bcedfa9217fe185ed574e5/R/order_draws.R#L26

So if we just ask it to make sure draws are consecutive and ordered (but not to re-order them) by setting `order = FALSE`, the slice is skipped and time is against constant in number of variables:

```r
bench_mark_n(repair_draws(x, order = FALSE), x = x_unrepaired)
# # A tibble: 4 × 14
#       n expression                          min median `itr/sec` mem_alloc `gc/sec`
#   <int> <bch:expr>                     <bch:tm> <bch:>     <dbl> <bch:byt>    <dbl>
# 1    10 repair_draws(x, order = FALSE)   2.47ms 2.63ms      364.     567KB     0   
# 2   100 repair_draws(x, order = FALSE)   2.49ms 2.71ms      359.     567KB     0   
# 3  1000 repair_draws(x, order = FALSE)   2.46ms 2.62ms      377.     567KB     2.33
# 4 10000 repair_draws(x, order = FALSE)   2.48ms 2.66ms      367.     567KB     0   
# # ℹ 7 more variables: n_itr <int>, n_gc <dbl>, total_time <bch:tm>, result <list>,
# #   memory <list>, time <list>, gc <list>
```

One obvious question then is, can this line instead be `.x <- repair_draws(.x, order = FALSE)`:

https://github.com/stan-dev/posterior/blob/59f4e6cbdddb9bb7b0bcedfa9217fe185ed574e5/R/summarise_draws.R#L170

I don't see why not, since we're just summarizing draws after this anyway (in fact, I'm not totally clear on why this line is needed at all). It might be worth looking at where `repair_draws()` is used throughout the codebase and seeing if there are places we can either drop it or at least let `order = FALSE`.

On the other hand, I'm not even convinced `repair_draws` is the problem here. I assume that cmdstan is returning ordered draws, in which case the repair will not be expensive. When I profile `summarise_draws()`, as I increase the number of variables the expensive operations seem to be summary functions themselves, like `rhat` and `ess_tail`, not `repair_draws`...

**Comment by paul-buerkner** [comment]
Thank you for your thorough investigation! ordering of the draws is required to compute Rhat and ESS since they need are based on autocorrelation measures. But I agree, we could use repair_draws less agressively. And if the user messes up the draw order, not make it our problem (or at least less so). How shall we proceed with the issue at hand and the repair_draws discussion?

**Comment by mjskay** [comment]
Maybe use of `repair_draws` should be a separate issue. For this issue, a reprex showing a fast version of the desired computation for comparison against summarise_draws might be helpful for profiling to figure out where the slowdown is. I'd also want to check that cmdstanr is returning well-ordered draws, because if it is, repair_draws should not be the issue here...

**Comment by huffyhenry** [comment]
Thank you Paul and Matthew for following up and my apologies for the late reply. I missed the GitHub notification.

It is not clear that `repair_draws` is the culprit. Based on the linked issues, `as_draws_array` is more likely, especially since my draws come untouched from `cmdstanr`. The only thing I know for sure is that the bottleneck is before the parallelised code, because my script hangs with only one core busy.

I'm re-running my code now over a fork of `posterior` with print statements and will report asap on which line it hangs.

**Comment by huffyhenry** [comment]
The draws are in whatever format `cmdstanr` keeps them in the workflow in the original post. As per https://github.com/stan-dev/cmdstanr/blob/ab30e076952548007826e906155fc8b0d725d651/R/fit.R#L749 and `?cmdstanr::draws`, this should be `draws_array`, because I have not specified the format or altered any defaults.

**Comment by mjskay** [comment]
Cool, thanks. Yeah, then I wouldn't expect repair_draws() or as_draws_array() to be the issue unless the draws returned by cmdstanr are unordered (or we are incorrectly detecting them as unordered when they aren't...). Will be curious to see the results of your tests (thanks for doing that btw!)

**Comment by huffyhenry** [comment]
The test has been running for 16h without triggering any of the print statements. The issue is likely with `cmdstanr`, not `posterior`. Unlike for optimized models, `cmdstanr::summary` for MCMC fits does some work inside `draws` before invoking `posterior`: https://github.com/stan-dev/cmdstanr/blob/ab30e076952548007826e906155fc8b0d725d651/R/fit.R#L1252 and may be hanging there. To confirm, the whole model needs to be refitted with a rigged `cmdstanr`, because the code gets serialized together with the fit object. Thanks for your patience as I work on this.

**Comment by huffyhenry** [comment]
I ran some more tests. Summarising 450 draws from the following Stan model:
````stan
data {
  int N;
}

generated quantities {
  vector[N] y;
  
  for (i in 1:N){
    y[i] = std_normal_rng();
  }
}
````
with N=2e6 takes 10-12h on a single core. This is a long time, but it is spent where it should be, in the main loop calculating the diagnostics. Up to you to decide if this is fast enough. Of course Stan users can always use the much faster `stansummary` from the command line.

My actual model still needs to be refitted to diagnose the problem there. Feel free to close this issue and I am going to re-open it if I can confirm that the problem is with `posterior`. Many thanks again for your help and for the nice package.

**Comment by mjskay** [comment]
Thanks for this and for investigating it!

**Comment by paul-buerkner** [comment]
Thank you from my side as well! Closing this for now.
