### ISSUE TITLE
Errors when `rvar` is made from a data frame

### ISSUE THREAD

**Issue by mattansb** [stan-dev/posterior#363]
Some funny things happen when an rvar is made from a data frame. To make a long story short, these can all be traced back to this:

```R
x <- data.frame(
  x1 = rnorm(1000),
  x2 = rnorm(1000)
)


# Seems to work, but tends to throw errors...
r <- posterior::rvar(x, nchains = 2)
r
#> rvar<500,2>[2] mean ± sd:
#>            x1            x2 
#> 0.021 ± 1.03  0.013 ± 0.99

str(r)
#> Error in dim(.draws) <- c(.dim[1], prod(.dim[-1])) : 
#>   dims [product 2000] do not match the length of object [2]
```

```R

# If you first convert to a matrix, everything is fine:
r <- posterior::rvar(as.matrix(x), nchains = 2)
r
#> rvar<500,2>[2] mean ± sd:
#>            x1            x2 
#> 0.021 ± 1.03  0.013 ± 0.99

str(r)
#>  rvar<500,2>[2]  0.021 ± 1.03  0.013 ± 0.99
#>  - dimnames(*)=List of 1
#>   ..$ : chr [1:2] "x1" "x2"
```

**Comment by mjskay** [comment]
Heh, oh yeah that definitely shouldn't allow you to do that.

**Comment by mjskay** [comment]
Thanks for raising this, added a PR to fix. Basically, you should not be able to input a data.frame into `rvar()`. If all the columns in the data frame are of the same type, convert to a matrix first (as you did), and if they aren't, consider using `as_draws_rvars()` instead of `rvar()` to convert each column to an `rvar` instead of the entire data frame to a single `rvar`.

**Comment by mattansb** [comment]
Thanks!
